### ISSUE TITLE
Get

### ISSUE THREAD

**Issue by fioronileo** [ravi-kaushish/node-red-contrib-sftp-ssh2#1]
I tested List and Put, everything is ok.
Get does not work.

localFilePath is missing in the command description (sftp.get(remoteFilePath, [useCompression], [encoding], [addtionalOptions]);

How to set the destination (path+filename) ?

Error: get: Bad path: : .: permission denied

**Comment by Nonobis** [comment]
i have fixed the get in this https://github.com/ravi-kaushish/node-red-contrib-sftp-ssh2/pull/2.

For usage 

msg.localFilePath = "c:\\test.json"
msg.remoteFilePath = "/Remote/test.json"

if @ravi-kaushish can check and merge this PR.. :)

**Comment by ravi-kaushish** [comment]
th ePR was merged and a new version was realeased. Thanks for your contribution
