### ISSUE TITLE
Where do I put the privateKey?

### ISSUE THREAD

**Issue by number005** [ravi-kaushish/node-red-contrib-sftp-ssh2#3]
Where do I put the privateKey?

**Comment by ravi-kaushish** [comment]
<p>privateKey property for the node module can be overriden by msg.sshPrivateKey or by using msg.privateKey properties.</p>

**Comment by number005** [comment]
Thank you. But then password should not be mandatory, as it is provided a privateKey.

**Comment by ravi-kaushish** [comment]
No it is not, you can try putting anything in there
