### ISSUE TITLE
server parameters

### ISSUE THREAD

**Issue by fabrix76** [ravi-kaushish/node-red-contrib-sftp-ssh2#4]
Hello, is there any way to pass, via msg attributes remote, host, username and password?

**Comment by ravi-kaushish** [comment]
Not yet, but I can add that ability, if you need it.

Let me know if you want me to add it, i'll add and publish a new version.

**Comment by fabrix76** [comment]
I think it could be a powerfull enhancement. Today if you have a variable list of hosts to interact in ssh (or in sftp) you need to use scripting, with this enhancement it became possible to act fully inside node-red logic without script.

Thank you for your interest in my request

**Comment by ravi-kaushish** [comment]
Thanks for the suggestion, it'll be added and published by eod tomorrow. 

Will let you know once done.

**Comment by ravi-kaushish** [comment]
Added overridable for all config properties

The host, port, username, password, privateKey can be override by using any msg.sftp_ssh2_config.propertyName.

host => msg.sftp_ssh2_config.host
port => msg.sftp_ssh2_config.port
username => msg.sftp_ssh2_config.username
password => msg.sftp_ssh2_config.password
privateKey => msg.sftp_ssh2_config.privateKey


Please install 0.1.3 and let me know if you encounter any issues.

Regards,
Ravi
